"""add position to favorites

Revision ID: cf03a1f14a18
Revises: 51567dff6cba
Create Date: 2026-03-16 13:57:43.407774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf03a1f14a18'
down_revision: Union[str, Sequence[str], None] = '51567dff6cba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorites', sa.Column('position', sa.Integer(), nullable=False))
    op.create_unique_constraint('uq_favorite_user_position', 'favorites', ['user_id', 'position'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_favorite_user_position', 'favorites', type_='unique')
    op.drop_column('favorites', 'position')
    # ### end Alembic commands ###
